version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  server:
    restart: on-failure
    # build: ./
    image: hoangtung2354/codecollab-server:latest
    environment:
      - REDIS_URL=${REDIS_URL_DEV}
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - '3000:3000'
networks:
  network1:
    name: codecollab
    external: true