version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  server:
    restart: on-failure
    # build: ./
    image: codecollab/server:latest
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - '3000:3000'